use fvm_ipld_encoding::ipld_block::IpldBlock;
use fvm_ipld_encoding::repr::*;
use fvm_ipld_encoding::serde_bytes;
use fvm_ipld_encoding::tuple::{Deserialize_tuple, Serialize_tuple};
use fvm_shared::address::Address;
use fvm_shared::clock::ChainEpoch;
use fvm_shared::econ::TokenAmount;
use fvm_shared::MethodNum;
use ipc_gateway::SubnetID;

/// ID used in the builtin-actors bundle manifest
pub const MANIFEST_ID: &str = "ipc_subnet_actor";

/// Optional leaving coefficient to penalize
/// validators leaving the subnet.
// It should be a float between 0-1 but
// setting it to 1_u64 for now for convenience.
// This will change once we figure out the econ model.
pub const LEAVING_COEFF: u64 = 1;
pub const TESTING_ID: u64 = 339;

#[derive(Clone, Debug, Serialize_tuple, Deserialize_tuple, PartialEq, Eq)]
pub struct Validator {
    pub addr: Address,
    pub net_addr: String,
}

#[derive(Clone, Debug, Serialize_tuple, Deserialize_tuple, PartialEq, Eq)]
pub struct Votes {
    pub validators: Vec<Address>,
}

/// Consensus types supported by hierarchical consensus
#[derive(PartialEq, Eq, Clone, Copy, Debug, Deserialize_repr, Serialize_repr)]
#[repr(u64)]
pub enum ConsensusType {
    Delegated,
    PoW,
    Tendermint,
    Mir,
    FilecoinEC,
    Dummy,
}

#[derive(PartialEq, Eq, Clone, Copy, Debug, Deserialize_repr, Serialize_repr)]
#[repr(i32)]
pub enum Status {
    Instantiated,
    Active,
    Inactive,
    Terminating,
    Killed,
}

#[derive(Clone, Debug, Serialize_tuple, Deserialize_tuple, PartialEq, Eq)]
pub struct ConstructParams {
    pub parent: SubnetID,
    pub name: String,
    pub ipc_gateway_addr: u64,
    pub consensus: ConsensusType,
    pub min_validator_stake: TokenAmount,
    pub min_validators: u64,
    pub finality_threshold: ChainEpoch,
    pub check_period: ChainEpoch,
    // genesis is no longer generated by the actor
    // on-the-fly, but it is accepted as a construct
    // param
    #[serde(with = "serde_bytes")]
    pub genesis: Vec<u8>,
}

#[derive(Clone, Debug, Serialize_tuple, Deserialize_tuple, PartialEq, Eq)]
pub struct JoinParams {
    pub validator_net_addr: String,
}

pub(crate) struct CrossActorPayload {
    pub to: Address,
    pub method: MethodNum,
    pub params: Option<IpldBlock>,
    pub value: TokenAmount,
}

impl CrossActorPayload {
    pub fn new(
        to: Address,
        method: MethodNum,
        params: Option<IpldBlock>,
        value: TokenAmount,
    ) -> Self {
        Self {
            to,
            method,
            params,
            value,
        }
    }
}
